name: Continuous Delivery
on:
  push:
    branches: [master]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      # 1. Autenticarse con GCP usando un Service Account
      - uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      # 2. Configurar Docker para usar Artifact Registry
      - run: gcloud auth configure-docker us-central1-docker.pkg.dev

      # 3. Build y push de la imagen
      - run: |
          docker build -t us-central1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/latam-repo/api:$GITHUB_SHA .
          docker push us-central1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/latam-repo/api:$GITHUB_SHA